-- Donnees partagees par les clients 1.12, 2.4.3 et 3.3.5.
-- Les noms sont affiches en francais. Les valeurs "command" des zones
-- restent les cles anglaises utilisees par la table game_tele du serveur.

TeleportMenuData = TeleportMenuData or {}

local data = TeleportMenuData

local function AddFly(minVersion, region, faction, id, name)
	table.insert(data, {
		kind = "fly",
		minVersion = minVersion,
		region = region,
		faction = faction,
		id = id,
		name = name,
	})
end

local function AddCity(minVersion, region, faction, command, name)
	table.insert(data, {
		kind = "city",
		minVersion = minVersion,
		region = region,
		faction = faction,
		command = command,
		name = name,
	})
end

-- ---------------------------------------------------------------------------
-- Vanilla / Azeroth (1.12 et versions suivantes)
-- ---------------------------------------------------------------------------

-- Royaumes de l'Est - Alliance
AddFly(1, "eastern", "Alliance", 2, "Hurlevent")
AddFly(1, "eastern", "Alliance", 4, "Colline des Sentinelles, Marche de l'Ouest")
AddFly(1, "eastern", "Alliance", 5, "Comté-du-Lac, Les Carmines")
AddFly(1, "eastern", "Alliance", 6, "Forgefer, Dun Morogh")
AddFly(1, "eastern", "Alliance", 7, "Port de Menethil, Les Paluns")
AddFly(1, "eastern", "Alliance", 8, "Thelsamar, Loch Modan")
AddFly(1, "eastern", "Alliance", 12, "Sombre-comté, Bois de la Pénombre")
AddFly(1, "eastern", "Alliance", 14, "Austrivage, Contreforts de Hautebrande")
AddFly(1, "eastern", "Alliance", 16, "Refuge de l'Ornière, Hautes-terres d'Arathi")
AddFly(1, "eastern", "Alliance", 19, "Baie-du-Butin, Vallée de Strangleronce")
AddFly(1, "eastern", "Alliance", 43, "Nid-de-l'Aigle, Les Hinterlands")
AddFly(1, "eastern", "Alliance", 45, "Rempart-du-Néant, Terres foudroyées")
AddFly(1, "eastern", "Alliance", 66, "Camp du Noroît, Maleterres de l'Ouest")
AddFly(1, "eastern", "Alliance", 67, "Chapelle de l'Espoir de Lumière, Maleterres de l'Est")
AddFly(1, "eastern", "Alliance", 71, "Veille de Morgan, Steppes ardentes")
AddFly(1, "eastern", "Alliance", 74, "Halte du Thorium, Gorge des Vents brûlants")
AddFly(1, "eastern", "Alliance", 195, "Camp rebelle, Vallée de Strangleronce")

-- Royaumes de l'Est - Horde
AddFly(1, "eastern", "Horde", 10, "Le Sépulcre, Forêt des Pins-Argentés")
AddFly(1, "eastern", "Horde", 11, "Fossoyeuse")
AddFly(1, "eastern", "Horde", 13, "Moulin-de-Tarren, Contreforts de Hautebrande")
AddFly(1, "eastern", "Horde", 17, "Trépas-d'Orgrim, Hautes-terres d'Arathi")
AddFly(1, "eastern", "Horde", 18, "Baie-du-Butin, Vallée de Strangleronce")
AddFly(1, "eastern", "Horde", 20, "Grom'gol, Vallée de Strangleronce")
AddFly(1, "eastern", "Horde", 21, "Kargath, Terres ingrates")
AddFly(1, "eastern", "Horde", 56, "Pierrêche, Marais des Chagrins")
AddFly(1, "eastern", "Horde", 68, "Chapelle de l'Espoir de Lumière, Maleterres de l'Est")
AddFly(1, "eastern", "Horde", 70, "Corniche des Flammes, Steppes ardentes")
AddFly(1, "eastern", "Horde", 75, "Halte du Thorium, Gorge des Vents brûlants")
AddFly(1, "eastern", "Horde", 76, "Village des Vengebroches, Les Hinterlands")

-- Kalimdor - Commun
AddFly(1, "kalimdor", "Commun", 79, "Refuge des Marshal, Cratère d'Un'Goro")
AddFly(1, "kalimdor", "Commun", 80, "Cabestan, Les Tarides")
AddFly(1, "kalimdor", "Commun", 166, "Sanctuaire d'Émeraude, Gangrebois")
AddFly(1, "kalimdor", "Commun", 179, "Bourbe-à-brac, Marécage d'Âprefange")

-- Kalimdor - Alliance
AddFly(1, "kalimdor", "Alliance", 26, "Auberdine, Sombrivage")
AddFly(1, "kalimdor", "Alliance", 27, "Village de Rut'theran, Teldrassil")
AddFly(1, "kalimdor", "Alliance", 28, "Astranaar, Orneval")
AddFly(1, "kalimdor", "Alliance", 31, "Thalanaar, Féralas")
AddFly(1, "kalimdor", "Alliance", 32, "Île de Theramore, Marécage d'Âprefange")
AddFly(1, "kalimdor", "Alliance", 33, "Pic des Serres-Rocheuses, Serres-Rocheuses")
AddFly(1, "kalimdor", "Alliance", 37, "Combe de Nijel, Désolace")
AddFly(1, "kalimdor", "Alliance", 39, "Gadgetzan, Tanaris")
AddFly(1, "kalimdor", "Alliance", 41, "Bastion de Pennelune, Féralas")
AddFly(1, "kalimdor", "Alliance", 49, "Reflet-de-Lune")
AddFly(1, "kalimdor", "Alliance", 52, "Long-guet, Berceau-de-l'Hiver")
AddFly(1, "kalimdor", "Alliance", 62, "Havrenuit, Reflet-de-Lune")
AddFly(1, "kalimdor", "Alliance", 64, "Halte de Talrendis, Azshara")
AddFly(1, "kalimdor", "Alliance", 65, "Clairière de Griffebranche, Gangrebois")
AddFly(1, "kalimdor", "Alliance", 73, "Fort cénarien, Silithus")
AddFly(1, "kalimdor", "Alliance", 93, "Guet du Sang, Île de Brume-Sang")
AddFly(1, "kalimdor", "Alliance", 94, "L'Exodar")
AddFly(1, "kalimdor", "Alliance", 167, "Chant des forêts, Orneval")

-- Kalimdor - Horde
AddFly(1, "kalimdor", "Horde", 22, "Les Pitons-du-Tonnerre")
AddFly(1, "kalimdor", "Horde", 23, "Orgrimmar")
AddFly(1, "kalimdor", "Horde", 25, "La Croisée, Les Tarides")
AddFly(1, "kalimdor", "Horde", 29, "Retraite de Roche-Soleil, Serres-Rocheuses")
AddFly(1, "kalimdor", "Horde", 30, "Poste de Librevent, Mille pointes")
AddFly(1, "kalimdor", "Horde", 38, "Proie-de-l'Ombre, Désolace")
AddFly(1, "kalimdor", "Horde", 40, "Gadgetzan, Tanaris")
AddFly(1, "kalimdor", "Horde", 42, "Camp Mojache, Féralas")
AddFly(1, "kalimdor", "Horde", 44, "Valormok, Azshara")
AddFly(1, "kalimdor", "Horde", 48, "Poste de la Vénéneuse, Gangrebois")
AddFly(1, "kalimdor", "Horde", 53, "Long-guet, Berceau-de-l'Hiver")
AddFly(1, "kalimdor", "Horde", 55, "Mur-de-Fougères, Marécage d'Âprefange")
AddFly(1, "kalimdor", "Horde", 58, "Avant-poste de Zoram'gar, Orneval")
AddFly(1, "kalimdor", "Horde", 61, "Poste de Bois-brisé, Orneval")
AddFly(1, "kalimdor", "Horde", 63, "Havrenuit, Reflet-de-Lune")
AddFly(1, "kalimdor", "Horde", 69, "Reflet-de-Lune")
AddFly(1, "kalimdor", "Horde", 72, "Fort cénarien, Silithus")
AddFly(1, "kalimdor", "Horde", 77, "Camp Taurajo, Les Tarides")

-- ---------------------------------------------------------------------------
-- The Burning Crusade (2.4.3 et 3.3.5)
-- ---------------------------------------------------------------------------

-- Nouveaux trajets dans les Royaumes de l'Est
AddFly(2, "eastern", "Commun", 205, "Collines de la Cognée, Terres fantômes")
AddFly(2, "eastern", "Commun", 383, "Rivière Thondroril, Maleterres de l'Ouest")
AddFly(2, "eastern", "Horde", 82, "Lune-d'Argent")
AddFly(2, "eastern", "Horde", 83, "Tranquillien, Terres fantômes")
AddFly(2, "eastern", "Horde", 384, "La Barricade, Clairières de Tirisfal")

-- Outreterre - Commun
AddFly(2, "outland", "Commun", 122, "Zone 52, Raz-de-Néant")
AddFly(2, "outland", "Commun", 128, "Shattrath")
AddFly(2, "outland", "Commun", 139, "Foudreflèche, Raz-de-Néant")
AddFly(2, "outland", "Commun", 140, "Autel de Sha'tar, Vallée d'Ombrelune")
AddFly(2, "outland", "Commun", 150, "Cosmovrille, Raz-de-Néant")
AddFly(2, "outland", "Commun", 159, "Sanctum des étoiles, Vallée d'Ombrelune")
AddFly(2, "outland", "Commun", 160, "Bosquet éternel, Les Tranchantes")
AddFly(2, "outland", "Commun", 213, "Port des Confins du soleil, Île de Quel'Danas")

-- Outreterre - Alliance
AddFly(2, "outland", "Alliance", 100, "Bastion de l'Honneur, Péninsule des Flammes infernales")
AddFly(2, "outland", "Alliance", 101, "Temple de Telhamat, Péninsule des Flammes infernales")
AddFly(2, "outland", "Alliance", 117, "Telredor, Marécage de Zangar")
AddFly(2, "outland", "Alliance", 119, "Telaar, Nagrand")
AddFly(2, "outland", "Alliance", 124, "Bastion des Marteaux-Hardis, Vallée d'Ombrelune")
AddFly(2, "outland", "Alliance", 125, "Sylvanaar, Les Tranchantes")
AddFly(2, "outland", "Alliance", 129, "La Porte des ténèbres, Péninsule des Flammes infernales")
AddFly(2, "outland", "Alliance", 149, "Halte du Fracas, Péninsule des Flammes infernales")
AddFly(2, "outland", "Alliance", 156, "Poste de Toshley, Les Tranchantes")
AddFly(2, "outland", "Alliance", 164, "Havre d'Orebor, Marécage de Zangar")

-- Outreterre - Horde
AddFly(2, "outland", "Horde", 99, "Thrallmar, Péninsule des Flammes infernales")
AddFly(2, "outland", "Horde", 102, "Guet de l'Épervier, Péninsule des Flammes infernales")
AddFly(2, "outland", "Horde", 118, "Zabra'jin, Marécage de Zangar")
AddFly(2, "outland", "Horde", 120, "Garadar, Nagrand")
AddFly(2, "outland", "Horde", 123, "Village d'Ombrelune, Vallée d'Ombrelune")
AddFly(2, "outland", "Horde", 126, "Bastion des Sire-tonnerre, Les Tranchantes")
AddFly(2, "outland", "Horde", 127, "Fort des Brise-Pierres, Forêt de Terokkar")
AddFly(2, "outland", "Horde", 130, "La Porte des ténèbres, Péninsule des Flammes infernales")
AddFly(2, "outland", "Horde", 141, "Crête Brise-échine, Péninsule des Flammes infernales")
AddFly(2, "outland", "Horde", 142, "Trépas du saccageur, Péninsule des Flammes infernales")
AddFly(2, "outland", "Horde", 151, "Poste du Rat des marais, Marécage de Zangar")
AddFly(2, "outland", "Horde", 163, "Mok'Nathal, Les Tranchantes")

-- ---------------------------------------------------------------------------
-- Wrath of the Lich King (3.3.5 uniquement)
-- ---------------------------------------------------------------------------

-- Norfendre - Commun
AddFly(3, "northrend", "Commun", 226, "Bouclier Transitus, Frimarra")
AddFly(3, "northrend", "Commun", 252, "Temple du Repos du ver, Désolation des dragons")
AddFly(3, "northrend", "Commun", 289, "Escarpement d'Ambre, Toundra Boréenne")
AddFly(3, "northrend", "Commun", 294, "Moa'ki, Désolation des dragons")
AddFly(3, "northrend", "Commun", 295, "Kamagua, Fjord Hurlant")
AddFly(3, "northrend", "Commun", 296, "Unu'pe, Toundra Boréenne")
AddFly(3, "northrend", "Commun", 304, "Séjour d'Argent, Zul'Drak")
AddFly(3, "northrend", "Commun", 305, "Guet d'Ébène, Zul'Drak")
AddFly(3, "northrend", "Commun", 306, "La Brèche de Lumière, Zul'Drak")
AddFly(3, "northrend", "Commun", 307, "Zim'Torga, Zul'Drak")
AddFly(3, "northrend", "Commun", 308, "Le Cœur du fleuve, Bassin de Sholazar")
AddFly(3, "northrend", "Commun", 309, "Camp de base de Nesingwary, Bassin de Sholazar")
AddFly(3, "northrend", "Commun", 310, "Dalaran")
AddFly(3, "northrend", "Commun", 320, "K3, Les pics Foudroyés")
AddFly(3, "northrend", "Commun", 325, "Cime de la Mort, La Couronne de glace")
AddFly(3, "northrend", "Commun", 326, "Ulduar, Les pics Foudroyés")
AddFly(3, "northrend", "Commun", 327, "Refuge de Rochecombe, Les pics Foudroyés")
AddFly(3, "northrend", "Commun", 331, "Dubra'Jin, Zul'Drak")
AddFly(3, "northrend", "Commun", 334, "L'avant-garde d'Argent, La Couronne de glace")
AddFly(3, "northrend", "Commun", 340, "Enceinte du tournoi d'Argent, La Couronne de glace")

-- Norfendre - Alliance
AddFly(3, "northrend", "Alliance", 183, "Port-Valgarde, Fjord Hurlant")
AddFly(3, "northrend", "Alliance", 184, "Fort Hardivar, Fjord Hurlant")
AddFly(3, "northrend", "Alliance", 185, "Donjon de la Garde de l'Ouest, Fjord Hurlant")
AddFly(3, "northrend", "Alliance", 244, "Donjon de Garde-hiver, Désolation des dragons")
AddFly(3, "northrend", "Alliance", 245, "Donjon de la Bravoure, Toundra Boréenne")
AddFly(3, "northrend", "Alliance", 246, "Piste d'atterrissage de Spumelevier, Toundra Boréenne")
AddFly(3, "northrend", "Alliance", 247, "Repos des étoiles, Désolation des dragons")
AddFly(3, "northrend", "Alliance", 251, "Bastion Fordragon, Désolation des dragons")
AddFly(3, "northrend", "Alliance", 253, "Gîte Ambrepin, Les Grisonnes")
AddFly(3, "northrend", "Alliance", 255, "Brigade de la Marche de l'Ouest, Les Grisonnes")
AddFly(3, "northrend", "Alliance", 321, "Fort du Givre, Les pics Foudroyés")
AddFly(3, "northrend", "Alliance", 336, "Surplomb de Coursevent, Forêt du Chant de cristal")

-- Norfendre - Horde
AddFly(3, "northrend", "Horde", 190, "Nouvelle-Agamand, Fjord Hurlant")
AddFly(3, "northrend", "Horde", 191, "Accostage de la Vengeance, Fjord Hurlant")
AddFly(3, "northrend", "Horde", 192, "Camp Sabot-d'Hiver, Fjord Hurlant")
AddFly(3, "northrend", "Horde", 248, "Camp des Apothicaires, Fjord Hurlant")
AddFly(3, "northrend", "Horde", 249, "Camp Oneqwah, Les Grisonnes")
AddFly(3, "northrend", "Horde", 250, "Bastion de la Conquête, Les Grisonnes")
AddFly(3, "northrend", "Horde", 254, "Vexevenin, Désolation des dragons")
AddFly(3, "northrend", "Horde", 256, "Marteau d'Agmar, Désolation des dragons")
AddFly(3, "northrend", "Horde", 257, "Bastion Chanteguerre, Toundra Boréenne")
AddFly(3, "northrend", "Horde", 258, "Taunka'le, Toundra Boréenne")
AddFly(3, "northrend", "Horde", 259, "Avant-poste Bor'gorok, Toundra Boréenne")
AddFly(3, "northrend", "Horde", 260, "Avant-garde kor'kron, Désolation des dragons")
AddFly(3, "northrend", "Horde", 323, "Site d'accident de Grom'arsh, Les pics Foudroyés")
AddFly(3, "northrend", "Horde", 324, "Camp Tunka'lo, Les pics Foudroyés")
AddFly(3, "northrend", "Horde", 337, "Quartier général de Saccage-soleil, Forêt du Chant de cristal")

-- ---------------------------------------------------------------------------
-- Destinations .tele de la base CMaNGOS TBC.
-- Les alias courts (ab, aq20, brd, BT, etc.) ne sont pas ajoutes lorsqu'une
-- commande longue designe deja le meme lieu. La saisie libre reste disponible
-- pour les commandes personnalisees du serveur.
-- ---------------------------------------------------------------------------

-- Azeroth classique
AddCity(1, "eastern", "Alliance", "AeriePeak", "Nid-de-l'Aigle")
AddCity(1, "eastern", "Alliance", "AlgazStation", "Station d'Algaz")
AddCity(1, "eastern", "Commun", "AlteracMountains", "Montagnes d'Alterac")
AddCity(1, "eastern", "Commun", "AlteracValley", "Vallée d'Alterac")
AddCity(1, "eastern", "Alliance", "AlteracValleyAlliance", "Vallée d'Alterac — point Alliance")
AddCity(1, "eastern", "Horde", "AlteracValleyHorde", "Vallée d'Alterac — point Horde")
AddCity(1, "eastern", "Alliance", "Ambermill", "Moulin-de-l'Ambre")
AddCity(1, "eastern", "Commun", "AngorFortress", "Forteresse d'Angor")
AddCity(1, "eastern", "Commun", "ArathiBasin", "Bassin d'Arathi")
AddCity(1, "eastern", "Alliance", "ArathiBasinAlliance", "Bassin d'Arathi — point Alliance")
AddCity(1, "eastern", "Horde", "ArathiBasinHorde", "Bassin d'Arathi — point Horde")
AddCity(1, "eastern", "Commun", "ArathiHighlands", "Hautes-terres d'Arathi")
AddCity(1, "kalimdor", "Commun", "Ashenvale", "Orneval")
AddCity(1, "kalimdor", "Alliance", "Astranaar", "Astranaar")
AddCity(1, "kalimdor", "Alliance", "Auberdine", "Auberdine")
AddCity(1, "kalimdor", "Commun", "Azshara", "Azshara")
AddCity(1, "kalimdor", "Commun", "AzsharaCrater", "Cratère d'Azshara")
AddCity(1, "eastern", "Commun", "Badlands", "Terres ingrates")
AddCity(1, "kalimdor", "Commun", "Barrens", "Les Tarides")
AddCity(1, "eastern", "Commun", "Beggar'sHaunt", "Repaire du Mendiant")
AddCity(1, "kalimdor", "Commun", "BlackfathomDeeps", "Profondeurs de Brassenoire")
AddCity(1, "eastern", "Commun", "BlackrockDepths", "Profondeurs de Rochenoire")
AddCity(1, "eastern", "Commun", "BlackrockMountain", "Mont Rochenoire")
AddCity(1, "eastern", "Commun", "BlackrockSpire", "Pic Rochenoire")
AddCity(1, "eastern", "Commun", "BlackrockStronghold", "Fort Rochenoire")
AddCity(1, "eastern", "Commun", "BlackwingLair", "Repaire de l'Aile noire")
AddCity(1, "eastern", "Commun", "BlastedLands", "Terres foudroyées")
AddCity(1, "kalimdor", "Horde", "BloodhoofVillage", "Sabot-de-Sang")
AddCity(1, "kalimdor", "Horde", "BloodvenomPost", "Poste de la Vénéneuse")
AddCity(1, "eastern", "Commun", "BootyBay", "Baie-du-Butin")
AddCity(1, "kalimdor", "Commun", "BoughShadow", "Rameau de l'Ombre")
AddCity(1, "kalimdor", "Horde", "BrackenwallVillage", "Mur-de-Fougères")
AddCity(1, "eastern", "Alliance", "BrewnallVillage", "Village des Brasse-Tout")
AddCity(1, "eastern", "Horde", "Brill", "Brill")
AddCity(1, "eastern", "Commun", "BurningSteppes", "Steppes ardentes")
AddCity(1, "eastern", "Commun", "CaerDarrow", "Caer Darrow")
AddCity(1, "kalimdor", "Horde", "CampAparaje", "Camp Aparaje")
AddCity(1, "kalimdor", "Horde", "CampMojache", "Camp Mojache")
AddCity(1, "kalimdor", "Horde", "CampNarache", "Camp Narache")
AddCity(1, "kalimdor", "Horde", "CampTaurajo", "Camp Taurajo")
AddCity(1, "kalimdor", "Commun", "CavernsOfTime", "Grottes du Temps")
AddCity(1, "kalimdor", "Commun", "CenarionHold", "Fort cénarien")
AddCity(1, "eastern", "Alliance", "ColdridgeValley", "Vallée des Frigères")
AddCity(1, "eastern", "Commun", "Corin'sCrossing", "Croisée de Corin")
AddCity(1, "eastern", "Commun", "Crypt", "Crypte")
AddCity(1, "eastern", "Commun", "Dalaran", "Dalaran")
AddCity(1, "eastern", "Alliance", "Darkshire", "Sombre-comté")
AddCity(1, "kalimdor", "Commun", "Darkshore", "Sombrivage")
AddCity(1, "kalimdor", "Alliance", "Darnassus", "Darnassus")
AddCity(1, "eastern", "Commun", "DeadwindPass", "Défilé de Deuillevent")
AddCity(1, "eastern", "Horde", "Deathknell", "Le Glas")
AddCity(1, "kalimdor", "Commun", "Desolace", "Désolace")
AddCity(1, "kalimdor", "Commun", "DireMaulEast", "Hache-tripes — Est")
AddCity(1, "kalimdor", "Commun", "DireMaulNorth", "Hache-tripes — Nord")
AddCity(1, "kalimdor", "Commun", "DireMaulWest", "Hache-tripes — Ouest")
AddCity(1, "kalimdor", "Alliance", "Dolanaar", "Dolanaar")
AddCity(1, "eastern", "Commun", "DreadmaulHold", "Bastion Cognepeur")
AddCity(1, "eastern", "Commun", "DreadmaulRock", "Rocher des Cognepeurs")
AddCity(1, "kalimdor", "Commun", "DreamBough", "Bosquet du Rêve")
AddCity(1, "eastern", "Alliance", "DunAlgaz", "Dun Algaz")
AddCity(1, "eastern", "Alliance", "DunGarok", "Dun Garok")
AddCity(1, "eastern", "Alliance", "DunModr", "Dun Modr")
AddCity(1, "eastern", "Commun", "DunMorogh", "Dun Morogh")
AddCity(1, "eastern", "Commun", "DurnholdeKeep", "Fort-de-Durn")
AddCity(1, "kalimdor", "Commun", "Durotar", "Durotar")
AddCity(1, "kalimdor", "Horde", "DurotarZeppelin", "Zeppelin de Durotar")
AddCity(1, "eastern", "Commun", "Duskwood", "Bois de la Pénombre")
AddCity(1, "kalimdor", "Commun", "DustwallowMarsh", "Marécage d'Âprefange")
AddCity(1, "eastern", "Commun", "EasternPlaguelands", "Maleterres de l'Est")
AddCity(1, "eastern", "Commun", "EastwallGate", "Porte du Mur est")
AddCity(1, "kalimdor", "Horde", "EchoIsles", "Îles de l'Écho")
AddCity(1, "eastern", "Commun", "ElwynnForest", "Forêt d'Elwynn")
AddCity(1, "kalimdor", "Commun", "EmeraldDream", "Rêve d'émeraude")
AddCity(1, "kalimdor", "Commun", "EmeraldForest", "Forêt d'Émeraude")
AddCity(1, "kalimdor", "Commun", "EmeraldSanctuary", "Sanctuaire d'Émeraude")
AddCity(1, "kalimdor", "Commun", "EmeraldStatue", "Statue d'émeraude")
AddCity(1, "kalimdor", "Commun", "Everlook", "Long-guet")
AddCity(1, "kalimdor", "Alliance", "FeathermoonStronghold", "Bastion de Pennelune")
AddCity(1, "kalimdor", "Commun", "Felwood", "Gangrebois")
AddCity(1, "eastern", "Commun", "FenrisIsle", "Île de Fenris")
AddCity(1, "kalimdor", "Commun", "Feralas", "Féralas")
AddCity(1, "eastern", "Horde", "FlameCrest", "Corniche des Flammes")
AddCity(1, "kalimdor", "Horde", "FreewindPost", "Poste de Librevent")
AddCity(1, "kalimdor", "Commun", "Gadgetzan", "Gadgetzan")
AddCity(1, "kalimdor", "Commun", "GatesOfAhn'Qiraj", "Portes d'Ahn'Qiraj")
AddCity(1, "kalimdor", "Horde", "GhostWalkerPost", "Poste de Rôdeur-fantôme")
AddCity(1, "kalimdor", "Commun", "GMIsland", "Île des MJ")
AddCity(1, "kalimdor", "Commun", "GMPrison", "Prison des MJ")
AddCity(1, "eastern", "Commun", "Gnomeregan", "Gnomeregan")
AddCity(1, "eastern", "Alliance", "Goldshire", "Comté-de-l'Or")
AddCity(1, "eastern", "Commun", "GrimBatol", "Grim Batol")
AddCity(1, "eastern", "Horde", "Grom'golBaseCamp", "Campement Grom'gol")
AddCity(1, "eastern", "Commun", "GurubashiArena", "Arène des Gurubashi")
AddCity(1, "eastern", "Horde", "Hammerfall", "Trépas-d'Orgrim")
AddCity(1, "eastern", "Commun", "Hearthglen", "Âtreval")
AddCity(1, "eastern", "Commun", "HillsbradFoothills", "Contreforts de Hautebrande")
AddCity(1, "kalimdor", "Commun", "HyjalSummit", "Sommet d'Hyjal")
AddCity(1, "eastern", "Alliance", "Ironforge", "Forgefer")
AddCity(1, "eastern", "Commun", "Jintha'Alor", "Jintha'Alor")
AddCity(1, "eastern", "Commun", "Karazhan", "Karazhan")
AddCity(1, "eastern", "Horde", "Kargath", "Kargath")
AddCity(1, "eastern", "Alliance", "Kharanos", "Kharanos")
AddCity(1, "eastern", "Alliance", "Lakeshire", "Comté-du-Lac")
AddCity(1, "eastern", "Commun", "Light'sHopeChapel", "Chapelle de l'Espoir de Lumière")
AddCity(1, "eastern", "Commun", "LochModan", "Loch Modan")
AddCity(1, "eastern", "Commun", "LothosRiftwaker", "Lothos Ouvrefaille")
AddCity(1, "kalimdor", "Commun", "Maraudon", "Maraudon")
AddCity(1, "kalimdor", "Commun", "MaraudonOrange", "Maraudon — entrée orange")
AddCity(1, "kalimdor", "Commun", "MaraudonPurple", "Maraudon — entrée pourpre")
AddCity(1, "kalimdor", "Commun", "Marshal'sRefuge", "Refuge des Marshal")
AddCity(1, "eastern", "Alliance", "MenethilHarbor", "Port de Menethil")
AddCity(1, "kalimdor", "Commun", "MirageRaceway", "Piste des Mirages")
AddCity(1, "eastern", "Commun", "MoltenCore", "Cœur du Magma")
AddCity(1, "eastern", "Commun", "Moonbrook", "Ruisselune")
AddCity(1, "kalimdor", "Commun", "Moonglade", "Reflet-de-Lune")
AddCity(1, "kalimdor", "Horde", "MoongladeHordeFlypoint", "Reflet-de-Lune — point de vol Horde")
AddCity(1, "kalimdor", "Horde", "Mor'shanBaseCamp", "Camp de base de Mor'shan")
AddCity(1, "eastern", "Alliance", "Morgan'sVigil", "Veille de Morgan")
AddCity(1, "kalimdor", "Commun", "Mudsprocket", "Bourbe-à-brac")
AddCity(1, "kalimdor", "Commun", "Mulgore", "Mulgore")
AddCity(1, "eastern", "Commun", "Naxxramas", "Naxxramas")
AddCity(1, "eastern", "Alliance", "NethergardeKeep", "Rempart-du-Néant")
AddCity(1, "kalimdor", "Commun", "Nighthaven", "Havrenuit")
AddCity(1, "kalimdor", "Alliance", "Nijel'sPoint", "Combe de Nijel")
AddCity(1, "eastern", "Alliance", "NorthshireValley", "Vallée de Comté-du-Nord")
AddCity(1, "kalimdor", "Commun", "OldHillsbradFoothills", "Hautebrande d'antan")
AddCity(1, "kalimdor", "Commun", "Onyxia'sLair", "Repaire d'Onyxia")
AddCity(1, "eastern", "Commun", "OrbOfCommand", "Orbe de commandement")
AddCity(1, "kalimdor", "Horde", "Orgrimmar", "Orgrimmar")
AddCity(1, "eastern", "Commun", "Plaguewood", "Pestebois")
AddCity(1, "eastern", "Commun", "PyrewoodVillage", "Bois-du-Bûcher")
AddCity(1, "eastern", "Alliance", "Quel'DanilLodge", "Gîte de Quel'Danil")
AddCity(1, "kalimdor", "Commun", "RagefireChasm", "Gouffre de Ragefeu")
AddCity(1, "kalimdor", "Commun", "Ratchet", "Cabestan")
AddCity(1, "eastern", "Commun", "RavenHill", "Colline-aux-Corbeaux")
AddCity(1, "eastern", "Commun", "RavenholdtManor", "Manoir de Ravenholdt")
AddCity(1, "kalimdor", "Commun", "RazorfenDowns", "Souilles de Tranchebauge")
AddCity(1, "kalimdor", "Commun", "RazorfenKraul", "Kraal de Tranchebauge")
AddCity(1, "kalimdor", "Horde", "RazorHill", "Tranchecolline")
AddCity(1, "eastern", "Alliance", "RebelCamp", "Camp rebelle")
AddCity(1, "eastern", "Commun", "RedridgeMountains", "Les Carmines")
AddCity(1, "eastern", "Alliance", "RefugePointe", "Refuge de l'Ornière")
AddCity(1, "eastern", "Horde", "RevantuskVillage", "Village des Vengebroches")
AddCity(1, "eastern", "Commun", "RuinsOfAlterac", "Ruines d'Alterac")
AddCity(1, "eastern", "Commun", "RuinsOfAndorhal", "Ruines d'Andorhal")
AddCity(1, "eastern", "Commun", "ScarletMonastery", "Monastère écarlate")
AddCity(1, "eastern", "Commun", "Scholomance", "Scholomance")
AddCity(1, "kalimdor", "Commun", "ScottTest", "Zone de test de Scott")
AddCity(1, "eastern", "Commun", "SearingGorge", "Gorge des Vents brûlants")
AddCity(1, "kalimdor", "Horde", "Sen'jinVillage", "Village de Sen'jin")
AddCity(1, "eastern", "Alliance", "SentinelHill", "Colline des Sentinelles")
AddCity(1, "eastern", "Commun", "Seradane", "Seradane")
AddCity(1, "eastern", "Commun", "ShadowFangKeep", "Donjon d'Ombrecroc")
AddCity(1, "kalimdor", "Alliance", "Shadowglen", "Sombrevallon")
AddCity(1, "kalimdor", "Horde", "ShadowpreyVillage", "Proie-de-l'Ombre")
AddCity(1, "kalimdor", "Commun", "ShadyRestInn", "Auberge du Repos ombragé")
AddCity(1, "kalimdor", "Commun", "Silithus", "Silithus")
AddCity(1, "eastern", "Commun", "SilverpineForest", "Forêt des Pins-Argentés")
AddCity(1, "eastern", "Commun", "SkulkRock", "Rocher du Crâne")
AddCity(1, "eastern", "Alliance", "Southshore", "Austrivage")
AddCity(1, "kalimdor", "Horde", "SplintertreePost", "Poste de Bois-brisé")
AddCity(1, "kalimdor", "Commun", "SteamwheedlePort", "Port Gentepression")
AddCity(1, "eastern", "Horde", "Stonard", "Pierrêche")
AddCity(1, "eastern", "Commun", "Stockade", "La Prison")
AddCity(1, "kalimdor", "Commun", "StonetalonMountains", "Serres-Rocheuses")
AddCity(1, "kalimdor", "Alliance", "StonetalonPeak", "Pic des Serres-Rocheuses")
AddCity(1, "eastern", "Commun", "Stonewatch", "Guet-de-Pierre")
AddCity(1, "eastern", "Alliance", "StonewroughtDam", "Barrage de Formepierre")
AddCity(1, "eastern", "Alliance", "Stormwind", "Hurlevent")
AddCity(1, "eastern", "Commun", "Strahnbrad", "Strahnbrad")
AddCity(1, "eastern", "Commun", "StranglethornVale", "Vallée de Strangleronce")
AddCity(1, "eastern", "Commun", "Stratholme", "Stratholme")
AddCity(1, "eastern", "Alliance", "StromgardeKeep", "Donjon de Stromgarde")
AddCity(1, "kalimdor", "Horde", "SunRockRetreat", "Retraite de Roche-Soleil")
AddCity(1, "eastern", "Commun", "SwampOfSorrows", "Marais des Chagrins")
AddCity(1, "kalimdor", "Alliance", "TalonbranchGlade", "Clairière de Griffebranche")
AddCity(1, "kalimdor", "Alliance", "TalrendisPoint", "Halte de Talrendis")
AddCity(1, "kalimdor", "Commun", "Tanaris", "Tanaris")
AddCity(1, "eastern", "Horde", "TarrenMill", "Moulin-de-Tarren")
AddCity(1, "kalimdor", "Commun", "Teldrassil", "Teldrassil")
AddCity(1, "eastern", "Commun", "TempleOfAtal'Hakkar", "Temple d'Atal'Hakkar")
AddCity(1, "eastern", "Commun", "Terrordale", "Val-Terreur")
AddCity(1, "kalimdor", "Alliance", "Thalanaar", "Thalanaar")
AddCity(1, "eastern", "Commun", "TheAltarOfZul", "Autel de Zul")
AddCity(1, "kalimdor", "Commun", "TheBlackMorass", "Le Noir Marécage")
AddCity(1, "eastern", "Horde", "TheBulwark", "La Barricade")
AddCity(1, "eastern", "Commun", "TheCauldron", "Le Chaudron")
AddCity(1, "kalimdor", "Horde", "TheCrossroads", "La Croisée")
AddCity(1, "eastern", "Commun", "TheDarkPortal", "La Porte des ténèbres")
AddCity(1, "eastern", "Commun", "TheDeadmines", "Les Mortemines")
AddCity(1, "kalimdor", "Commun", "TheForgottenCoast", "Côte oubliée")
AddCity(1, "eastern", "Commun", "TheFungalVale", "Val fongique")
AddCity(1, "eastern", "Commun", "TheGrindingQuarry", "Carrière de broyage")
AddCity(1, "eastern", "Alliance", "TheHarborage", "Le Refuge")
AddCity(1, "eastern", "Commun", "TheHinterlands", "Les Hinterlands")
AddCity(1, "eastern", "Commun", "TheLoch", "Le Loch")
AddCity(1, "eastern", "Alliance", "Thelsamar", "Thelsamar")
AddCity(1, "eastern", "Commun", "TheMarrisStead", "Ferme des Marris")
AddCity(1, "eastern", "Commun", "TheMoltenSpan", "Travée de lave")
AddCity(1, "kalimdor", "Alliance", "Theramore", "Theramore")
AddCity(1, "kalimdor", "Commun", "TheRuinsOfAhn'Qiraj", "Ruines d'Ahn'Qiraj")
AddCity(1, "kalimdor", "Commun", "TheScarabWall", "Mur du Scarabée")
AddCity(1, "eastern", "Horde", "TheSepulcher", "Le Sépulcre")
AddCity(1, "eastern", "Commun", "TheSunkenTemple", "Temple englouti")
AddCity(1, "eastern", "Commun", "TheTaintedScar", "Balafre impure")
AddCity(1, "kalimdor", "Commun", "TheTempleOfAhn'Qiraj", "Temple d'Ahn'Qiraj")
AddCity(1, "eastern", "Commun", "TheVice", "L'Étau")
AddCity(1, "eastern", "Commun", "ThoriumPoint", "Halte du Thorium")
AddCity(1, "kalimdor", "Commun", "ThousandNeedles", "Mille pointes")
AddCity(1, "kalimdor", "Horde", "ThunderBluff", "Les Pitons-du-Tonnerre")
AddCity(1, "kalimdor", "Commun", "TimbermawHold", "Repaire des Grumegueules")
AddCity(1, "eastern", "Commun", "TirisfalGlades", "Clairières de Tirisfal")
AddCity(1, "eastern", "Horde", "TirisfalGladesZeppelin", "Zeppelin des Clairières de Tirisfal")
AddCity(1, "eastern", "Commun", "TowerOfIlgalar", "Tour d'Ilgalar")
AddCity(1, "eastern", "Commun", "TwilightGrove", "Bosquet du Crépuscule")
AddCity(1, "eastern", "Commun", "Tyr'sHand", "Main de Tyr")
AddCity(1, "eastern", "Commun", "Uldaman", "Uldaman")
AddCity(1, "kalimdor", "Commun", "Un'GoroCrater", "Cratère d'Un'Goro")
AddCity(1, "eastern", "Horde", "Undercity", "Fossoyeuse")
AddCity(1, "kalimdor", "Horde", "ValleyOfTrials", "Vallée des Épreuves")
AddCity(1, "kalimdor", "Commun", "Valor'sRest", "Repos des Vaillants")
AddCity(1, "kalimdor", "Horde", "Valormok", "Valormok")
AddCity(1, "kalimdor", "Commun", "VerdantFields", "Champs verdoyants")
AddCity(1, "kalimdor", "Commun", "WailingCaverns", "Cavernes des Lamentations")
AddCity(1, "kalimdor", "Commun", "WarsongGulch", "Goulet des Chanteguerres")
AddCity(1, "kalimdor", "Alliance", "WarsongGulchAlliance", "Goulet des Chanteguerres — point Alliance")
AddCity(1, "kalimdor", "Horde", "WarsongGulchHorde", "Goulet des Chanteguerres — point Horde")
AddCity(1, "eastern", "Commun", "WesternPlaguelands", "Maleterres de l'Ouest")
AddCity(1, "eastern", "Commun", "Westfall", "Marche de l'Ouest")
AddCity(1, "eastern", "Commun", "Wetlands", "Les Paluns")
AddCity(1, "kalimdor", "Commun", "Winterspring", "Berceau-de-l'Hiver")
AddCity(1, "kalimdor", "Horde", "Zoram'garOutpost", "Avant-poste de Zoram'gar")
AddCity(1, "kalimdor", "Commun", "Zul'Farrak", "Zul'Farrak")
AddCity(1, "eastern", "Commun", "Zul'Gurub", "Zul'Gurub")

-- Royaumes de l'Est — contenu Burning Crusade
AddCity(2, "eastern", "Commun", "Deatholme", "Mortholme")
AddCity(2, "eastern", "Commun", "DuskwitherSpire", "Flèche de Coursevent")
AddCity(2, "eastern", "Commun", "EversongWoods", "Bois des Chants éternels")
AddCity(2, "eastern", "Horde", "FairbreezeVillage", "Brise-Clémente")
AddCity(2, "eastern", "Horde", "FalconwingSquare", "Place de l'Épervier")
AddCity(2, "eastern", "Commun", "Ghostlands", "Terres fantômes")
AddCity(2, "eastern", "Commun", "GoldenmistVillage", "Brume-d'Or")
AddCity(2, "eastern", "Commun", "KaraBack", "Karazhan — entrée arrière")
AddCity(2, "eastern", "Commun", "KaraFront", "Karazhan — entrée principale")
AddCity(2, "eastern", "Commun", "Nightbane", "Plaie-de-Nuit")
AddCity(2, "eastern", "Commun", "RuinsOfSilvermoon", "Ruines de Lune-d'Argent")
AddCity(2, "eastern", "Horde", "Saltheril'sHaven", "Havre de Saltheril")
AddCity(2, "eastern", "Commun", "SanctumOfTheMoon", "Sanctum de la Lune")
AddCity(2, "eastern", "Horde", "SanctumOfTheSun", "Sanctum du Soleil")
AddCity(2, "eastern", "Horde", "SilvermoonCity", "Lune-d'Argent")
AddCity(2, "eastern", "Commun", "SuncrownVillage", "Solcouronne")
AddCity(2, "eastern", "Horde", "SunstriderIsle", "Île de Haut-Soleil")
AddCity(2, "eastern", "Commun", "TheDeadScar", "Malebrèche")
AddCity(2, "eastern", "Horde", "TheSunspire", "La Flèche solaire")
AddCity(2, "eastern", "Commun", "Tor'Watha", "Tor'Watha")
AddCity(2, "eastern", "Horde", "Tranquillien", "Tranquillien")
AddCity(2, "eastern", "Horde", "WestSanctum", "Sanctum occidental")
AddCity(2, "eastern", "Commun", "Zul'Aman", "Zul'Aman")

-- Kalimdor — contenu Burning Crusade
AddCity(2, "kalimdor", "Alliance", "AmmenVale", "Vallée d'Ammen")
AddCity(2, "kalimdor", "Commun", "Axxarien", "Axxarien")
AddCity(2, "kalimdor", "Alliance", "AzureWatch", "Guet d'Azur")
AddCity(2, "kalimdor", "Commun", "AzuremystIsle", "Île de Brume-Azur")
AddCity(2, "kalimdor", "Alliance", "BloodWatch", "Guet du Sang")
AddCity(2, "kalimdor", "Commun", "BloodcurseIsle", "Île du Sang maudit")
AddCity(2, "kalimdor", "Commun", "BloodmystIsle", "Île de Brume-Sang")
AddCity(2, "kalimdor", "Alliance", "CrashSite", "Site du crash")
AddCity(2, "kalimdor", "Commun", "Hyjal", "Hyjal")
AddCity(2, "kalimdor", "Alliance", "HyjalAlliance", "Hyjal — point Alliance")
AddCity(2, "kalimdor", "Horde", "HyjalHorde", "Hyjal — point Horde")
AddCity(2, "kalimdor", "Alliance", "HyjalHuman", "Hyjal — point humain")
AddCity(2, "kalimdor", "Alliance", "HyjalNightElf", "Hyjal — point elfe de la nuit")
AddCity(2, "kalimdor", "Horde", "HyjalOrc", "Hyjal — point orc")
AddCity(2, "kalimdor", "Alliance", "Kessel'sCrossing", "Croisée de Kessel")
AddCity(2, "kalimdor", "Commun", "Nazzivian", "Nazzivian")
AddCity(2, "kalimdor", "Commun", "SilvermystIsle", "Île de Brume-Argent")
AddCity(2, "kalimdor", "Alliance", "StillpineHold", "Repaire des Calmepins")
AddCity(2, "kalimdor", "Alliance", "TheExodar", "L'Exodar")
AddCity(2, "kalimdor", "Commun", "TheVectorCoil", "La Bobine vectorielle")
AddCity(2, "kalimdor", "Commun", "WyrmscarIsland", "Île Balafre-du-ver")

-- Outreterre et contenu de niveau 70
AddCity(2, "outland", "Alliance", "AllerianStronghold", "Bastion allérien")
AddCity(2, "outland", "Commun", "AltarOfSha'tar", "Autel de Sha'tar")
AddCity(2, "outland", "Commun", "Area52", "Zone 52")
AddCity(2, "outland", "Commun", "AuchenaiCrypts", "Cryptes Auchenaï")
AddCity(2, "outland", "Commun", "Auchindoun", "Auchindoun")
AddCity(2, "outland", "Commun", "Bash'irLanding", "Point d'ancrage de Bash'ir")
AddCity(2, "outland", "Commun", "BlackTemple", "Temple noir")
AddCity(2, "outland", "Commun", "Blade'sEdgeMountains", "Les Tranchantes")
AddCity(2, "outland", "Commun", "BladespireHold", "Bastion de Flèchelame")
AddCity(2, "outland", "Commun", "BloodmaulOutpost", "Avant-poste de la Masse-sanglante")
AddCity(2, "outland", "Commun", "CelestialRidge", "Crête céleste")
AddCity(2, "outland", "Commun", "CenarionPost", "Poste cénarien")
AddCity(2, "outland", "Commun", "CenarionRefuge", "Refuge cénarien")
AddCity(2, "outland", "Commun", "CenarionThicket", "Fourré cénarien")
AddCity(2, "outland", "Commun", "CircleOfBloodArena", "Arène du Cercle de sang")
AddCity(2, "outland", "Commun", "CoilfangReservoir", "Réservoir de Glissecroc")
AddCity(2, "outland", "Commun", "Death'sDoor", "Porte de la Mort")
AddCity(2, "outland", "Commun", "EclipsePoint", "Halte de l'Éclipse")
AddCity(2, "outland", "Commun", "Eco-DomeFarfield", "Écodôme des Terres lointaines")
AddCity(2, "outland", "Commun", "Eco-DomeMidrealm", "Écodôme du Royaume médian")
AddCity(2, "outland", "Commun", "Eco-DomeSutheron", "Écodôme de Sutheron")
AddCity(2, "outland", "Commun", "Evergrove", "Bosquet éternel")
AddCity(2, "outland", "Commun", "ExpeditionArmory", "Armurerie de l'Expédition")
AddCity(2, "outland", "Commun", "EyeOfTheStorm", "Œil du cyclone")
AddCity(2, "outland", "Alliance", "EyeOfTheStormAlliance", "Œil du cyclone — point Alliance")
AddCity(2, "outland", "Horde", "EyeOfTheStormHorde", "Œil du cyclone — point Horde")
AddCity(2, "outland", "Horde", "FalconWatch", "Guet de l'Épervier")
AddCity(2, "outland", "Commun", "FirewingPoint", "Halte Aile-de-feu")
AddCity(2, "outland", "Horde", "Garadar", "Garadar")
AddCity(2, "outland", "Commun", "Grangol'varVillage", "Village de Grangol'var")
AddCity(2, "outland", "Commun", "Grishnath", "Grishnath")
AddCity(2, "outland", "Commun", "Gruul'sLair", "Repaire de Gruul")
AddCity(2, "outland", "Commun", "Halaa", "Halaa")
AddCity(2, "outland", "Commun", "HellfireCitadel", "Citadelle des Flammes infernales")
AddCity(2, "outland", "Commun", "HellfirePeninsula", "Péninsule des Flammes infernales")
AddCity(2, "outland", "Commun", "HellfireRamparts", "Remparts des Flammes infernales")
AddCity(2, "outland", "Alliance", "HonorHold", "Bastion de l'Honneur")
AddCity(2, "outland", "Commun", "IsleOfQuel'Danas", "Île de Quel'Danas")
AddCity(2, "outland", "Commun", "Kil'sorrowFortress", "Forteresse Kil'sorrau")
AddCity(2, "outland", "Commun", "Kirin'VarVillage", "Village de Kirin'Var")
AddCity(2, "outland", "Horde", "Mag'harPost", "Poste Mag'har")
AddCity(2, "outland", "Commun", "Magisters'Terrace", "Terrasse des Magistères")
AddCity(2, "outland", "Commun", "Magtheridon'sLair", "Repaire de Magtheridon")
AddCity(2, "outland", "Commun", "ManaTombs", "Tombes-mana")
AddCity(2, "outland", "Commun", "ManaforgeCoruu", "Manaforge Coruu")
AddCity(2, "outland", "Commun", "ManaforgeDuro", "Manaforge Duro")
AddCity(2, "outland", "Commun", "ManaforgeUltris", "Manaforge Ultris")
AddCity(2, "outland", "Horde", "Mok'NathalVillage", "Village Mok'Nathal")
AddCity(2, "outland", "Commun", "Nagrand", "Nagrand")
AddCity(2, "outland", "Commun", "NesingwarySafari", "Safari de Nesingwary")
AddCity(2, "outland", "Commun", "Netherstorm", "Raz-de-Néant")
AddCity(2, "outland", "Commun", "NetherwingLedge", "Escarpement de l'Aile-du-Néant")
AddCity(2, "outland", "Commun", "Ogri'la", "Ogri'la")
AddCity(2, "outland", "Alliance", "OreborHarborage", "Havre d'Orebor")
AddCity(2, "outland", "Commun", "Oshu'gun", "Oshu'gun")
AddCity(2, "outland", "Commun", "Outland", "Outreterre")
AddCity(2, "outland", "Commun", "PoolsOfAggonar", "Bassins d'Aggonar")
AddCity(2, "outland", "Commun", "Raven'sWood", "Bois aux Corbeaux")
AddCity(2, "outland", "Commun", "Razaan'sLanding", "Point d'ancrage de Razaan")
AddCity(2, "outland", "Horde", "Reaver'sFall", "Trépas du saccageur")
AddCity(2, "outland", "Commun", "RefugeeCaravan", "Caravane de réfugiés")
AddCity(2, "outland", "Commun", "RingOfBlood", "Arène de sang")
AddCity(2, "outland", "Commun", "SanctumOfTheStars", "Sanctum des étoiles")
AddCity(2, "outland", "Commun", "SerpentshrineCavern", "Caverne du sanctuaire du Serpent")
AddCity(2, "outland", "Commun", "SethekkHalls", "Les salles des Sethekk")
AddCity(2, "outland", "Commun", "ShadowLabyrinth", "Labyrinthe des Ombres")
AddCity(2, "outland", "Horde", "ShadowmoonVillage", "Village d'Ombrelune")
AddCity(2, "outland", "Commun", "ShartuulsTransporter", "Transporteur de Shartuul")
AddCity(2, "outland", "Commun", "Shattrath", "Shattrath")
AddCity(2, "outland", "Horde", "SpinebreakerPost", "Poste de Brise-échine")
AddCity(2, "outland", "Commun", "Sporeggar", "Sporeggar")
AddCity(2, "outland", "Horde", "StonebreakerHold", "Fort des Brise-Pierres")
AddCity(2, "outland", "Commun", "SunfuryHold", "Bastion de Solfurie")
AddCity(2, "outland", "Commun", "SunspringPost", "Poste de Berceau-de-l'Été")
AddCity(2, "outland", "Commun", "SunwellPlateau", "Plateau du Puits de soleil")
AddCity(2, "outland", "Horde", "SwampratPost", "Poste du Rat des marais")
AddCity(2, "outland", "Alliance", "Sylvanaar", "Sylvanaar")
AddCity(2, "outland", "Alliance", "Telaar", "Telaar")
AddCity(2, "outland", "Alliance", "Telredor", "Telredor")
AddCity(2, "outland", "Commun", "TempestKeep", "Donjon de la Tempête")
AddCity(2, "outland", "Alliance", "TempleOfTelhamat", "Temple de Telhamat")
AddCity(2, "outland", "Commun", "TerokkarForest", "Forêt de Terokkar")
AddCity(2, "outland", "Commun", "TheArcatraz", "L'Arcatraz")
AddCity(2, "outland", "Commun", "TheBloodFurnace", "La Fournaise du sang")
AddCity(2, "outland", "Commun", "TheBotanica", "La Botanica")
AddCity(2, "outland", "Commun", "TheDeadMire", "Le Bourbier mort")
AddCity(2, "outland", "Commun", "TheEye", "L'Œil")
AddCity(2, "outland", "Commun", "TheMechanar", "Le Méchanar")
AddCity(2, "outland", "Commun", "TheRingOfTrials", "Cercle des épreuves")
AddCity(2, "outland", "Commun", "TheShatteredHalls", "Les Salles brisées")
AddCity(2, "outland", "Commun", "TheSlavePens", "Les enclos aux esclaves")
AddCity(2, "outland", "Commun", "TheSpawningGlen", "La Clairière des pontes")
AddCity(2, "outland", "Commun", "TheStairOfDestiny", "Escalier du Destin")
AddCity(2, "outland", "Commun", "TheSteamvault", "Le Caveau de la vapeur")
AddCity(2, "outland", "Commun", "TheStormspire", "Foudreflèche")
AddCity(2, "outland", "Commun", "TheTwilightRidge", "Crête du Crépuscule")
AddCity(2, "outland", "Commun", "TheUnderbog", "La Basse-tourbière")
AddCity(2, "outland", "Horde", "Thrallmar", "Thrallmar")
AddCity(2, "outland", "Commun", "ThroneOfKil'jaeden", "Trône de Kil'jaeden")
AddCity(2, "outland", "Horde", "ThunderlordStronghold", "Bastion des Sire-tonnerre")
AddCity(2, "outland", "Alliance", "Toshley'sStation", "Poste de Toshley")
AddCity(2, "outland", "Commun", "Tuurem", "Tuurem")
AddCity(2, "outland", "Commun", "VeilRuuan", "Voile Ruuan")
AddCity(2, "outland", "Commun", "VekhaarStand", "Séjour de Vekh'aar")
AddCity(2, "outland", "Commun", "Warden'sCage", "Cage de la gardienne")
AddCity(2, "outland", "Alliance", "WildhammerStronghold", "Bastion des Marteaux-hardis")
AddCity(2, "outland", "Horde", "Zabra'jin", "Zabra'jin")
AddCity(2, "outland", "Commun", "Zangarmarsh", "Marécage de Zangar")
AddCity(2, "outland", "Commun", "ZeppelinCrash", "Site du zeppelin écrasé")
AddCity(2, "outland", "Horde", "Zeth'Gor", "Zeth'Gor")
AddCity(2, "outland", "Commun", "skettis", "Skettis")
